version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
       - 3306:3306
    volumes:
            - /home/sa_admin/Desktop/docker/sql57/mysql_data:/var/lib/mysql:rw
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - UPLOAD_LIMIT=2048000000
        # - PMA_ARBITRARY=1

        #command: --default-authentication-plugin=mysql_native_password
